app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"