# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app_bundle.service.listener:
        class: AppBundle\EventListener\CalendarEventListener
        arguments:
            ["@doctrine.orm.entity_manager", "@security.token_storage"]
        tags:
            - { name: 'kernel.event_listener', event: 'calendar.load_events', method: loadEvents }
    app_bundle.form.type.profil:
        class: AppBundle\Form\Type\ProfileFormType
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: form.type }

    user_event.service:
        class: AppBundle\Services\UserEventService
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]